services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: deepface-api
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "4912:4912"
    volumes:
      - .env:/app/.env
    networks:
      - homelabs

networks:
  homelabs:
    external: true